name: deploy-website
on: 
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # outputs:
    #   nodev: ${{ steps.node.outputs.version }}

    steps:
    - name: Checking out source code
      uses: actions/checkout@v3
    
    - name: Use Node 16.20.0
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.0'
        cache: npm
      
    - name: Install Dependencies
      run: npm install --legacy-peer-deps --save google-maps-react

    - name: Build Project
      run:  npm run build --if-present

    - name: Install rsync
      run: sudo apt-get install rsync

    - name: Deploy theme on server
      id: deploy
      uses: burnett01/rsync-deployments@6.0.0
      env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
          switches: '-avhz --progress --exclude-from=./deployment/exclude.txt --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r -oHostKeyAlgorithms=ssh-rsa --delete-after'
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"